resources:
  repositories:
  - repository: MyGitHubRepo # The name used to reference this repository in the checkout step
    type: github
    endpoint: MyFirstProject
    name: kag728/drafts

pr:
  branches:
    include:
    - master
    - releases/*
    exclude:
    - releases/old*
  drafts: true

pool: 'Default'

steps:
- checkout: self
- checkout: MyGitHubRepo

- script: dir $(Build.SourcesDirectory)
