resources:
  repositories:
  - repository: MyGitHubRepo # The name used to reference this repository in the checkout step
    type: github
    endpoint: MyFirstProject
    name: kag728/drafts
    trigger:  # CI trigger for this repository, no CI trigger if skipped (only works for Azure Repos)
      branches:
        include: [ master ] # branch names which will trigger a build
      tags:
        include: [refs/*]

pool: 'Default'

steps:
- checkout: self
- checkout: MyGitHubRepo

- script: dir $(Build.SourcesDirectory)
